export default {
  dark: {
    cartBackgroundColor: '#333b50',
    formBackgroundColor: '#424c66',

    buttonAlign: 'center',
    buttonColor: '#fff',
    buttonBoxColor: '#5b88de',
    buttonActiveBoxColor: '#4e7fdb',
    buttonHoverBoxColor: '#6891e1',
    buttonDisabledOpacity: '0.7',
    buttonBeforeColor: '#fff',
    buttonAfterColor: '#fff',

    checkboxColor: '#fff',
    checkboxHoverColor: '#06eaa7',
    checkboxCheckedColor: '#06eaa7',
    checkboxDisabledOpacity: '0.7',

    preloaderColor: 'rgba(255, 255, 255, 0.1)',
    preloaderSpinColor: '#06eaa7',

    inputBorderColor: 'rgba(255, 255, 255, 0.2)',
    inputBoxColor: 'transparent',
    inputColor: '#fff',
    inputDisabledOpacity: '0.5',
    inputErrorBorderColor: '#fc7e57',
    inputErrorBoxColor: '#fc7e57',
    inputErrorColor: '#fff',
    inputFocusBorderColor: '#06eaa7',
    inputFocusLabelColor: 'rgba(255, 255, 255, 0.3)',
    inputHoverBorderColor: 'rgba(255, 255, 255, 0.5)',
    inputLabelColor: 'rgba(255, 255, 255, 0.5)',

    selectBorderColor: 'rgba(255, 255, 255, 0.2)',
    selectBoxColor: 'transparent',
    selectColor: '#fff',
    selectDisabledOpacity: '0.5',
    selectFocusBorderColor: '#06eaa7',
    selectHoverBorderColor: 'rgba(255, 255, 255, 0.5)',
    selectOptionsBoxColor: 'transparent',
  },
  light: {
    cartBackgroundColor: '#F3F3F3',
    formBackgroundColor: '#fff',

    buttonAlign: 'center',
    buttonColor: '#fff',
    buttonBoxColor: '#5b88de',
    buttonActiveBoxColor: '#4e7fdb',
    buttonHoverBoxColor: '#6891e1',
    buttonDisabledOpacity: '0.7',
    buttonBeforeColor: '#fff',
    buttonAfterColor: '#fff',

    checkboxColor: '#fff',
    checkboxHoverColor: '#06eaa7',
    checkboxCheckedColor: '#06eaa7',
    checkboxDisabledOpacity: '0.7',

    preloaderColor: 'rgba(255, 255, 255, 0.1)',
    preloaderSpinColor: '#06eaa7',

    inputBorderColor: 'rgba(255, 255, 255, 0.2)',
    inputBoxColor: 'transparent',
    inputColor: '#fff',
    inputDisabledOpacity: '0.5',
    inputErrorBorderColor: '#fc7e57',
    inputErrorBoxColor: '#fc7e57',
    inputErrorColor: '#fff',
    inputFocusBorderColor: '#06eaa7',
    inputFocusLabelColor: 'rgba(255, 255, 255, 0.3)',
    inputHoverBorderColor: 'rgba(255, 255, 255, 0.5)',
    inputLabelColor: 'rgba(255, 255, 255, 0.5)',

    selectBorderColor: 'rgba(255, 255, 255, 0.2)',
    selectBoxColor: 'transparent',
    selectColor: '#fff',
    selectDisabledOpacity: '0.5',
    selectFocusBorderColor: '#06eaa7',
    selectHoverBorderColor: 'rgba(255, 255, 255, 0.5)',
    selectOptionsBoxColor: 'transparent',
  },
};
